{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment-tracker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deployment-tracker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "deployment-tracker.selectorLabels" . | nindent 4 }}
{{- end }}
